services:
  postgres:
    image: postgres:latest
    container_name: capital-allocation-db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: capital_allocation_db
    ports:
      - "5432:5432"